### ISSUE TITLE
kx, ky scaling

### ISSUE THREAD

**Issue by mckib2** [mckib2/phantominator#7]
It seems that BART's traj command uses different unit convention than mriphantom.  Which scaling is better to use?  Can we accommodate both?  Currently kspace_shepp_logan uses mriphantom convention @Tronic 

I don't feel very strongly either way, just need something that is consistent through the project and can be clearly communicated to users.

**Comment by Tronic** [comment]
I am a novice on this and cannot comment on which would be better. What's the rationale behind BART's scaling, or is that documented anywhere?

**Comment by mckib2** [comment]
The best documentation I know of is here: https://buildmedia.readthedocs.org/media/pdf/bart-doc/latest/bart-doc.pdf

From pg 8: "The unit of measurement for kspace trajectory is 1/FOV. For example, a valid kspace trajectory for a 192-by-128 image should be scaled such that the x-coordinates cover the range of -192/2 to 192/2 and y-coordinates cover the range of -128/2 to 128/2."

**Comment by mckib2** [comment]
Let's go ahead and leave as is now, and if something comes up later on down the road another issue can be opened.
