### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by merna17798** [mckib2/phantominator#8]
# CT phantom
from phantominator import shepp_logan
ph = shepp_logan(128)

# MR phantom (returns proton density, T1, and T2 maps)
M0, T1, T2 = shepp_logan((128, 128, 20), MR=True)
while i had runing the example i got this error although the liberary installed correctly

Traceback (most recent call last):
  File "c:/Users/pc/Desktop/mri/task1/phantom.py", line 2, in <module>
    from phantominator import shepp_logan
  File "C:\Users\pc\Anaconda3\lib\site-packages\phantominator\__init__.py", line 10, in <module>
    from .kspace import kspace_shepp_logan
  File "C:\Users\pc\Anaconda3\lib\site-packages\phantominator\kspace.py", line 7, in <module>
    from scipy.special import j1 # pylint: disable=E0611
  File "C:\Users\pc\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 634, in <module>
    from . import _ufuncs
ImportError: DLL load failed: The specified module could not be found.

**Comment by mckib2** [comment]
@merna17798 Sorry, just saw this.

Do you mind giving me some info:
- operating system
- Python version
- C++ compiler and version

**Comment by mckib2** [comment]
I'm guessing you're on windows using anaconda.  Looks like an issue with scipy import.  Does scipy work on your machine?

**Comment by merna17798** [comment]
Hey! First of all,thanks for your interest and to replay ... The real
hassle was I had used visual studio which have some conflict in running so
when I ran my file on anaconda prompt. It works
Thanks for your priceless time

**Comment by mckib2** [comment]
Glad you got it working, I'll go ahead and close this issue
