### ISSUE TITLE
Missing explanation in ct_shepp_logan.py, line 28

### ISSUE THREAD

**Issue by gaopinghai** [mckib2/phantominator#9]
First of all, thanks for your great work! I am new to CT reconstruction. I read many times about the Shepp-Logan Dataset in many places. But I never managed to download this Dataset until I got this package. This is the Shepp-Logan Dataset!

In the commit of `ct_shepp_logan` function, I think there is a missing line explaning the sixth column of E:
```python
E : array_like, optional
        For 2D: ex6 numeric matrix defining e ellipses.  The six
        columns of E are:
            - Length of the horizontal semiaxis of the ellipse
            - Length of the vertical semiaxis of the ellipse
            - x-coordinate of the center of the ellipse (in [-1, 1])
            - y-coordinate of the center of the ellipse (in [-1, 1])
            - Angle between the horizontal semiaxis of the ellipse
              and the x-axis of the image (in rad)
            - Gray value of this ellipse (int [0, 1])    # <<<<<<<<<<<<<<< I think this is the missing line
```
is it right? It will be my great honor if I can help to propose a pull requests afterwords. @mckib2

**Comment by mckib2** [comment]
Hi @PingHGao , thanks for spotting this!

It appears that the [first column (not the last)](https://github.com/mckib2/phantominator/blob/39daa5d4e9161ebe2bf1a911225a6325edeefd3a/phantominator/ct_shepp_logan.py#L114) of E holds the gray value of the ellipse.  I would be very excited to receive a pull request for this, let me know if I can be of assistance!
